Repository oclif/oclif, pull requests merged in 2024-04, with the labels that each got.

#1356 Add `override` modifier to static properties in generated commands
  templates/src/command.ts.ejs
Labels: cla:signed

#1357 Add `override` modifier to generated commands (#1356)
  templates/src/command.ts.ejs
Labels: cla:signed

#1358 feat: Add init command
  src/commands/init.ts
  templates/src/init/dev.cmd.ejs
  templates/src/init/dev.js.ejs
  templates/src/init/run.cmd.ejs
  templates/src/init/run.js.ejs
Labels: enhancement, cla:signed

#1366 feat: add init command (#1358)
  .github/workflows/test.yml
  package.json
  src/commands/generate.ts
  src/commands/init.ts
  src/generator.ts
  templates/src/init/dev.cmd.ejs
  templates/src/init/dev.js.ejs
  templates/src/init/run.cmd.ejs
  templates/src/init/run.js.ejs
  test/integration/cli.test.ts
  test/integration/init.test.ts
  test/integration/util.ts
Labels: cla:signed

#1368 fix: supporting paths with spaces whilst running chmod (#1367)
  src/commands/init.ts
Labels: cla:missing
