Repository oclif/oclif, pull requests merged in 2024-01, with the labels that each got.

#1229 fix: missing core yarn files
  src/tarballs/build.ts
Labels: cla:signed

#1230 fix: missing core yarn files (#1229)
  src/tarballs/build.ts
Labels: cla:signed

#1234 fix: readme command does not parse path correctly on windows
  src/commands/readme.ts
Labels: cla:signed

#1238 feat: add node.options
  src/tarballs/bin.ts
  src/tarballs/build.ts
  src/tarballs/config.ts
Labels: cla:signed

#1239 feat: add node.options (#1238)
  src/tarballs/bin.ts
  src/tarballs/build.ts
  src/tarballs/config.ts
Labels: cla:signed

#1215 feat: upgrade to use aws sdk v3
  package.json
  src/aws.ts
  test/helpers/helper.ts
  yarn.lock
Labels: enhancement, cla:signed

#1240 feat: upgrade to use aws api v3 (#1215)
  bin/dev.js
  bin/run.js
  package.json
  src/aws.ts
  src/commands/promote.ts
  src/tarballs/config.ts
  src/version-indexes.ts
  test/helpers/helper.ts
  yarn.lock
Labels: cla:signed

#1110 feat: Adds an option to specify compression used for pack:deb
  README.md
  src/commands/pack/deb.ts
Labels: cla:signed

#1241 feat: option to specify compression used for pack:deb (#1110)
  README.md
  src/commands/pack/deb.ts
Labels: cla:signed

#1267 fix: correct S3 key generation for /apt/./ During deb artifacts promotion (#1265) (#1266)
  src/commands/promote.ts
Labels: cla:signed

#1264 feat: deprecate and hide lock command
  src/commands/lock.ts
Labels: enhancement
