Repository oclif/oclif, pull requests merged in 2024-02, with the labels that each got.

#1283 Update win.ts and fix error by adding quotation marks
  src/commands/pack/win.ts
Labels: cla:missing

#1262 fix: make eslint plugin a dev dependency
  package.json
Labels: cla:signed

#1302 fix: sort generated package.json
  .github/workflows/test.yml
  package.json
  src/generators/cli.ts
  src/generators/command.ts
  src/generators/hook.ts
  src/tarballs/build.ts
  src/tarballs/node.ts
  tsconfig.json
  yarn.lock
Labels: enhancement
